# Form implementation generated from reading ui file 'ui/mainwindow.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1460, 708)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(1460, 708))
        MainWindow.setMaximumSize(QtCore.QSize(1460, 708))
        MainWindow.setStyleSheet("background-color: rgb(245, 250, 254);")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setMinimumSize(QtCore.QSize(1460, 708))
        self.centralwidget.setMaximumSize(QtCore.QSize(1460, 708))
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.sidebar_widget = QtWidgets.QWidget(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sidebar_widget.sizePolicy().hasHeightForWidth())
        self.sidebar_widget.setSizePolicy(sizePolicy)
        self.sidebar_widget.setMinimumSize(QtCore.QSize(224, 708))
        self.sidebar_widget.setMaximumSize(QtCore.QSize(224, 708))
        self.sidebar_widget.setStyleSheet("QWidget{\n"
"    background-color: rgb(39, 39, 39);\n"
"}\n"
"\n"
"QLabel{\n"
"    qproperty-alignment: AlignCenter;\n"
"    font-weight: bold;\n"
"    color: rgb(170, 170, 255);\n"
"}\n"
"\n"
"QPushButton{\n"
"    color: rgb(238, 238, 238);\n"
"    text-align: left;\n"
"    height: 30px;\n"
"    border: none;\n"
"    padding-left: 17px;\n"
"    border-top-right-radius: 10px;\n"
"    border-bottom-right-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:checked{\n"
"    font-weight: bold;\n"
"    background-color: rgb(91,91,133)\n"
"}")
        self.sidebar_widget.setObjectName("sidebar_widget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.sidebar_widget)
        self.verticalLayout_4.setContentsMargins(0, -1, 6, -1)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.header_label = QtWidgets.QLabel(parent=self.sidebar_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.header_label.sizePolicy().hasHeightForWidth())
        self.header_label.setSizePolicy(sizePolicy)
        self.header_label.setMinimumSize(QtCore.QSize(0, 28))
        self.header_label.setMaximumSize(QtCore.QSize(130, 28))
        self.header_label.setObjectName("header_label")
        self.horizontalLayout.addWidget(self.header_label)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.scroll_area = QtWidgets.QScrollArea(parent=self.sidebar_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scroll_area.sizePolicy().hasHeightForWidth())
        self.scroll_area.setSizePolicy(sizePolicy)
        self.scroll_area.setMinimumSize(QtCore.QSize(224, 665))
        self.scroll_area.setMaximumSize(QtCore.QSize(224, 708))
        self.scroll_area.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAsNeeded)
        self.scroll_area.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.scroll_area.setWidgetResizable(True)
        self.scroll_area.setObjectName("scroll_area")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 222, 663))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scroll_area.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_4.addWidget(self.scroll_area)
        self.gridLayout_2.addWidget(self.sidebar_widget, 0, 0, 1, 1)
        self.main_view = QtWidgets.QWidget(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.main_view.sizePolicy().hasHeightForWidth())
        self.main_view.setSizePolicy(sizePolicy)
        self.main_view.setMinimumSize(QtCore.QSize(1236, 708))
        self.main_view.setMaximumSize(QtCore.QSize(1236, 708))
        self.main_view.setStyleSheet("QWidget{\n"
"    background-color: rgb(49, 49, 49);\n"
"}")
        self.main_view.setObjectName("main_view")
        self.layoutWidget = QtWidgets.QWidget(parent=self.main_view)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 0, 1264, 711))
        self.layoutWidget.setObjectName("layoutWidget")
        self.main_hor_layout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.main_hor_layout.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetFixedSize)
        self.main_hor_layout.setContentsMargins(0, 0, 0, 0)
        self.main_hor_layout.setSpacing(0)
        self.main_hor_layout.setObjectName("main_hor_layout")
        self.main_vert_layout = QtWidgets.QVBoxLayout()
        self.main_vert_layout.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetFixedSize)
        self.main_vert_layout.setSpacing(0)
        self.main_vert_layout.setObjectName("main_vert_layout")
        self.labels_hor_layout = QtWidgets.QHBoxLayout()
        self.labels_hor_layout.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetFixedSize)
        self.labels_hor_layout.setContentsMargins(-1, -1, -1, 10)
        self.labels_hor_layout.setObjectName("labels_hor_layout")
        self.camera_label = QtWidgets.QLabel(parent=self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.camera_label.sizePolicy().hasHeightForWidth())
        self.camera_label.setSizePolicy(sizePolicy)
        self.camera_label.setMinimumSize(QtCore.QSize(528, 70))
        self.camera_label.setMaximumSize(QtCore.QSize(528, 70))
        self.camera_label.setStyleSheet("QLabel{\n"
"    qproperty-alignment: AlignLeft;\n"
"    margin-left: 37;\n"
"    padding-bottom: 10;\n"
"    padding-top: 35;\n"
"    padding-bottom: 0;\n"
"    font-weight: bold;\n"
"    color: rgb(91, 91, 133);\n"
"}\n"
"")
        self.camera_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading)
        self.camera_label.setObjectName("camera_label")
        self.labels_hor_layout.addWidget(self.camera_label)
        self.count_label = QtWidgets.QLabel(parent=self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.count_label.sizePolicy().hasHeightForWidth())
        self.count_label.setSizePolicy(sizePolicy)
        self.count_label.setMinimumSize(QtCore.QSize(528, 70))
        self.count_label.setMaximumSize(QtCore.QSize(528, 70))
        self.count_label.setStyleSheet("QLabel{\n"
"    qproperty-alignment: AlignRight;\n"
"    margin-right: 40;\n"
"    padding-top: 35;\n"
"    padding-bottom: 10;\n"
"    padding-bottom: 0;\n"
"    font-weight: bold;\n"
"    color: rgb(91, 91, 133);\n"
"}")
        self.count_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight)
        self.count_label.setObjectName("count_label")
        self.labels_hor_layout.addWidget(self.count_label)
        self.main_vert_layout.addLayout(self.labels_hor_layout)
        self.main_hor_layout.addLayout(self.main_vert_layout)
        self.gridLayout_2.addWidget(self.main_view, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.header_label.setText(_translate("MainWindow", "Select a camera:"))
        self.camera_label.setText(_translate("MainWindow", "Camera No.: 1"))
        self.count_label.setText(_translate("MainWindow", "Count: 0"))
