# Form implementation generated from reading ui file 'ui/sidebar.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(993, 525)
        MainWindow.setStyleSheet("background-color: rgb(245, 250, 254);")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.icon_name_widget = QtWidgets.QWidget(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.icon_name_widget.sizePolicy().hasHeightForWidth())
        self.icon_name_widget.setSizePolicy(sizePolicy)
        self.icon_name_widget.setMinimumSize(QtCore.QSize(230, 500))
        self.icon_name_widget.setMaximumSize(QtCore.QSize(230, 16777215))
        self.icon_name_widget.setStyleSheet("QWidget{\n"
"    background-color: rgb(39, 39, 39);\n"
"}\n"
"\n"
"QLabel{\n"
"    qproperty-alignment: AlignCenter;\n"
"    font-weight: bold;\n"
"    color: rgb(170, 170, 255);\n"
"}\n"
"\n"
"QPushButton{\n"
"    color: rgb(238, 238, 238);\n"
"    text-align: left;\n"
"    height: 30px;\n"
"    border: none;\n"
"    padding-left: 17px;\n"
"    border-top-right-radius: 10px;\n"
"    border-bottom-right-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:checked{\n"
"    font-weight: bold;\n"
"    background-color: rgb(91,91,133)\n"
"}")
        self.icon_name_widget.setObjectName("icon_name_widget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.icon_name_widget)
        self.verticalLayout_4.setContentsMargins(0, -1, 6, -1)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(-1, 7, -1, -1)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, -1, 5, -1)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.header_label = QtWidgets.QLabel(parent=self.icon_name_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.header_label.sizePolicy().hasHeightForWidth())
        self.header_label.setSizePolicy(sizePolicy)
        self.header_label.setMaximumSize(QtCore.QSize(130, 16777215))
        self.header_label.setObjectName("header_label")
        self.horizontalLayout_2.addWidget(self.header_label)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_2)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setContentsMargins(0, 8, 0, 10)
        self.verticalLayout_2.setSpacing(15)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.dashboard_button = QtWidgets.QPushButton(parent=self.icon_name_widget)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/dashboard_light.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.dashboard_button.setIcon(icon)
        self.dashboard_button.setIconSize(QtCore.QSize(27, 27))
        self.dashboard_button.setCheckable(True)
        self.dashboard_button.setAutoExclusive(True)
        self.dashboard_button.setObjectName("dashboard_button")
        self.verticalLayout_2.addWidget(self.dashboard_button)
        self.menu_button = QtWidgets.QPushButton(parent=self.icon_name_widget)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/hamburger_light.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.menu_button.setIcon(icon1)
        self.menu_button.setIconSize(QtCore.QSize(27, 27))
        self.menu_button.setCheckable(True)
        self.menu_button.setAutoExclusive(True)
        self.menu_button.setObjectName("menu_button")
        self.verticalLayout_2.addWidget(self.menu_button)
        self.verticalLayout_4.addLayout(self.verticalLayout_2)
        spacerItem2 = QtWidgets.QSpacerItem(20, 642, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_4.addItem(spacerItem2)
        self.settings_button = QtWidgets.QPushButton(parent=self.icon_name_widget)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/settings_light.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.settings_button.setIcon(icon2)
        self.settings_button.setIconSize(QtCore.QSize(27, 27))
        self.settings_button.setCheckable(True)
        self.settings_button.setAutoExclusive(True)
        self.settings_button.setObjectName("settings_button")
        self.verticalLayout_4.addWidget(self.settings_button)
        self.gridLayout_2.addWidget(self.icon_name_widget, 0, 0, 1, 1)
        self.main_view = QtWidgets.QWidget(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.main_view.sizePolicy().hasHeightForWidth())
        self.main_view.setSizePolicy(sizePolicy)
        self.main_view.setMinimumSize(QtCore.QSize(600, 400))
        self.main_view.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.main_view.setStyleSheet("QWidget{\n"
"    background-color: rgb(49, 49, 49);\n"
"}")
        self.main_view.setObjectName("main_view")
        self.stackedWidget = QtWidgets.QStackedWidget(parent=self.main_view)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 0, 760, 520))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stackedWidget.sizePolicy().hasHeightForWidth())
        self.stackedWidget.setSizePolicy(sizePolicy)
        self.stackedWidget.setMinimumSize(QtCore.QSize(600, 400))
        self.stackedWidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.stackedWidget.setObjectName("stackedWidget")
        self.gridLayout_2.addWidget(self.main_view, 0, 1, 1, 2)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.header_label.setText(_translate("MainWindow", "Navigate in CBA"))
        self.dashboard_button.setText(_translate("MainWindow", "Dashboard"))
        self.menu_button.setText(_translate("MainWindow", "Menu"))
        self.settings_button.setText(_translate("MainWindow", "Settings"))
